# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=1.2.0+26.1-2
maven_group=me.BigBou
archives_base_name=rei-search-bar-calculations
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.152.1+26.1.2
rei_version=26.1.819
yacl_version=3.9.4+26.1-fabric
modmenu_version=18.0.0-beta.1
